SolaCity_Inn1_MapScripts::
	.byte 0


SolaCity_Inn1_EventScript_Man::
# 4 "data/maps/SolaCity_Inn1/scripts.pory"
	msgbox SolaCity_Inn1_EventScript_Man_Text_0, MSGBOX_NPC
	return


SolaCity_Inn1_EventScript_Woman::
# 8 "data/maps/SolaCity_Inn1/scripts.pory"
	msgbox SolaCity_Inn1_EventScript_Woman_Text_0, MSGBOX_NPC
	return


SolaCity_Inn1_EventScript_Kid::
# 14 "data/maps/SolaCity_Inn1/scripts.pory"
	msgbox SolaCity_Inn1_EventScript_Kid_Text_0, MSGBOX_NPC
	return


SolaCity_Inn1_EventScript_Man_Text_0:
# 4 "data/maps/SolaCity_Inn1/scripts.pory"
	.string "We're here visiting from far away!$"

SolaCity_Inn1_EventScript_Woman_Text_0:
# 8 "data/maps/SolaCity_Inn1/scripts.pory"
	.string "Sola City is such a retreat compared to\n"
	.string "where we're from.\p"
	.string "How much is it to live here?$"

SolaCity_Inn1_EventScript_Kid_Text_0:
# 14 "data/maps/SolaCity_Inn1/scripts.pory"
	.string "Vacation is so always so exciting!$"
