SolaCity_SailorsHouse1_MapScripts::
	.byte 0


SolaCity_SailorsHouse1_EventScript_Sailor::
# 4 "data/maps/SolaCity_SailorsHouse1/scripts.pory"
	msgbox SolaCity_SailorsHouse1_EventScript_Sailor_Text_0, MSGBOX_NPC
	return


SolaCity_SailorsHouse1_EventScript_SailorWoman::
# 9 "data/maps/SolaCity_SailorsHouse1/scripts.pory"
	msgbox SolaCity_SailorsHouse1_EventScript_SailorWoman_Text_0, MSGBOX_NPC
	return


SolaCity_SailorsHouse1_EventScript_Sailor_Text_0:
# 4 "data/maps/SolaCity_SailorsHouse1/scripts.pory"
	.string "I've been out at sea for months now!\p"
	.string "It's so relaxing to be back home.$"

SolaCity_SailorsHouse1_EventScript_SailorWoman_Text_0:
# 9 "data/maps/SolaCity_SailorsHouse1/scripts.pory"
	.string "My husband was out for so long.\p"
	.string "I've missed him so much!$"
