SolaCity_Inn4_MapScripts::
	.byte 0


SolaCity_Inn4_EventScript_Kid::
# 4 "data/maps/SolaCity_Inn4/scripts.pory"
	msgbox SolaCity_Inn4_EventScript_Kid_Text_0, MSGBOX_NPC
	return


SolaCity_Inn4_EventScript_Kid2::
# 9 "data/maps/SolaCity_Inn4/scripts.pory"
	msgbox SolaCity_Inn4_EventScript_Kid2_Text_0, MSGBOX_NPC
	return


SolaCity_Inn4_EventScript_Kid_Text_0:
# 4 "data/maps/SolaCity_Inn4/scripts.pory"
	.string "When I grow up, I'm gonna be the best\n"
	.string "sailor in Sola City!$"

SolaCity_Inn4_EventScript_Kid2_Text_0:
# 9 "data/maps/SolaCity_Inn4/scripts.pory"
	.string "I heard the Captain once sailed all\n"
	.string "the way to the farthest islands and\n"
	.string "caught a Pokémon no one's ever seen before!\p"
	.string "Do you think I can be like him one day?$"
