SolaCity_Inn3_MapScripts::
	.byte 0


SolaCity_Inn3_EventScript_Man::
# 4 "data/maps/SolaCity_Inn3/scripts.pory"
	msgbox SolaCity_Inn3_EventScript_Man_Text_0, MSGBOX_NPC
	return


SolaCity_Inn3_EventScript_Man2::
# 9 "data/maps/SolaCity_Inn3/scripts.pory"
	msgbox SolaCity_Inn3_EventScript_Man2_Text_0, MSGBOX_NPC
	return


SolaCity_Inn3_EventScript_Man_Text_0:
# 4 "data/maps/SolaCity_Inn3/scripts.pory"
	.string "I'm so excited to take pictures of the\n"
	.string "oceanside view!$"

SolaCity_Inn3_EventScript_Man2_Text_0:
# 9 "data/maps/SolaCity_Inn3/scripts.pory"
	.string "What a gorgeous view Sola City gives us!$"
