SolaCity_SailorsHouse2_MapScripts::
	.byte 0


SolaCity_SailorsHouse2_EventScript_Sailor::
# 4 "data/maps/SolaCity_SailorsHouse2/scripts.pory"
	msgbox SolaCity_SailorsHouse2_EventScript_Sailor_Text_0, MSGBOX_NPC
	return


SolaCity_SailorsHouse2_EventScript_Kid::
# 9 "data/maps/SolaCity_SailorsHouse2/scripts.pory"
	msgbox SolaCity_SailorsHouse2_EventScript_Kid_Text_0, MSGBOX_NPC
	return


SolaCity_SailorsHouse2_EventScript_Sailor_Text_0:
# 4 "data/maps/SolaCity_SailorsHouse2/scripts.pory"
	.string "There's nothing I love more than sailing\n"
	.string "out there with my crew!$"

SolaCity_SailorsHouse2_EventScript_Kid_Text_0:
# 9 "data/maps/SolaCity_SailorsHouse2/scripts.pory"
	.string "When I grow up, I want to sail like my\n"
	.string "dad!$"
