CastbelleTown_BriansHouse_1F_MapScripts::
	.byte 0


CastbelleTown_BriansHouse_1F_EventScript_BriansMom::
# 4 "data/maps/CastbelleTown_BriansHouse_1F/scripts.pory"
	lock
# 5 "data/maps/CastbelleTown_BriansHouse_1F/scripts.pory"
	faceplayer
# 6 "data/maps/CastbelleTown_BriansHouse_1F/scripts.pory"
	msgbox CastbelleTown_BriansHouse_1F_EventScript_BriansMom_Text_0, MSGBOX_AUTOCLOSE
# 10 "data/maps/CastbelleTown_BriansHouse_1F/scripts.pory"
	faceoriginaldir
# 11 "data/maps/CastbelleTown_BriansHouse_1F/scripts.pory"
	release
	end


CastbelleTown_BriansHouse_1F_EventScript_BriansMom_Text_0:
# 6 "data/maps/CastbelleTown_BriansHouse_1F/scripts.pory"
	.string "sigh…\p"
	.string "Brian going on his own adventure…\p"
	.string "Please keep an eye on him, {PLAYER}.\n"
	.string "He considers you his best friend.$"
