CastbelleTown_BriansHouse_1F_MapScripts::
	.byte 0


CastbelleTown_BriansHouse_1F_EventScript_BriansMom::
# 4 "data/maps/CastbelleTown_BriansHouse_1F/scripts.pory"
	msgbox CastbelleTown_BriansHouse_1F_EventScript_BriansMom_Text_0, MSGBOX_NPC
	return


CastbelleTown_BriansHouse_1F_EventScript_BriansMom_Text_0:
# 4 "data/maps/CastbelleTown_BriansHouse_1F/scripts.pory"
	.string "sigh…\p"
	.string "Brian going on his own adventure…\p"
	.string "Please keep an eye on him, {PLAYER}.\n"
	.string "He considers you his best friend.$"
