SolaCity_Inn5_MapScripts::
	.byte 0


SolaCity_Inn5_EventScript_Fisherman::
# 4 "data/maps/SolaCity_Inn5/scripts.pory"
	msgbox SolaCity_Inn5_EventScript_Fisherman_Text_0, MSGBOX_NPC
	return


SolaCity_Inn5_EventScript_Fisherman_Text_0:
# 4 "data/maps/SolaCity_Inn5/scripts.pory"
	.string "Years ago, I heard the ocean sing a song\n"
	.string "to me.\p"
	.string "People thought I was crazy. But I know\n"
	.string "what I heard.$"
