SolaCity_House1_MapScripts::
	.byte 0


SolaCity_House1_EventScript_Woman::
# 4 "data/maps/SolaCity_House1/scripts.pory"
	msgbox SolaCity_House1_EventScript_Woman_Text_0, MSGBOX_NPC
	end


SolaCity_House1_EventScript_Woman_Text_0:
# 4 "data/maps/SolaCity_House1/scripts.pory"
	.string "Sola City is a nice calm, ocean side\n"
	.string "city.\p"
	.string "No wonder people from the mainland want\n"
	.string "to live here.\p"
	.string "It's so peaceful!$"
