name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 0
      UNUSED_ERROR: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout agbcc
        uses: actions/checkout@v2
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Install binutils
        run: |
          sudo apt update
          sudo apt install -y build-essential libpng-dev libelf-dev
        # build-essential and git are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install GTK 3
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev
        # used for building the patch

      - name: ROM
        env:
          MODERN: 1
          COMPARE: 0
        run: make -j${nproc} -O all

      - name: Test
        env:
          MODERN: 1
          TEST: 1
        run: |
          make -j${nproc} check

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc

      # Creating a patch file online
      - name: Download pokeemerald
        run: pwd && cd tools && git clone https://github.com/pret/pokeemerald
  
      - name: Install agbcc to pokeemerald
        run: pwd && cd tools && ls && cp -r agbcc pokeemerald/tools/ && cd pokeemerald && pwd
  
      - name: Build pokeemerald
        run: pwd && cd tools && cd pokeemerald && pwd && ls && make -j${nproc}

      - name: Build pokeemerald.bps
        run: |
          chmod -R 755 ./flips-linux
          ./flips-linux --create tools/pokeemerald/pokeemerald.gba pokeemerald.gba pokeemerald.bps

      - name: Upload patch
        uses: actions/upload-artifact@v3
        with:
          name: patch_file
          path: pokeemerald.bps

      - name: Send failure notification to Discord
        if: failure()   # Executes only if previous steps fail
        run: |
              curl -H "Content-Type: application/json" \
                   -X POST \
                   -d "{
                     \"embeds\": [{
                       \"title\": \"CI Job Failed\",
                       \"description\": \"A CI job has failed.\",
                       \"color\": 16711680,
                       \"fields\": [
                         {
                           \"name\": \"Commit name:\",
                           \"value\": \"${{ github.event.head_commit.message }}\",
                           \"inline\": false
                         },
                         {
                           \"name\": \"Commit hash:\",
                           \"value\": \"[${{ github.event.head_commit.id }}](${{ github.event.head_commit.url }})\",
                           \"inline\": false
                         },
                         {
                           \"name\": \"Committed by:\",
                           \"value\": \"[${{ github.actor }}](https://github.com/${{ github.actor }})\",
                           \"inline\": false
                         }
                       ]
                     }]
                   }" \
                   ${{ secrets.DISCORD_WEBHOOK }}
